### ISSUE TITLE
Define acceptable use and usage limits, and what happens if exceeded

### ISSUE THREAD

**Issue by evdb** [mysociety/popit#14]
For the hosted service what uses will we permit and what caps will be enforce. What do we do if these are exceeded.

possible things to consider:

* maximum size of database (in MB, or number of entries)
* API/web usage - number of hits, data transferred.
* data stored - just democracy related or will we host celebrities too? What won't we host?

**Comment by chrismytton** [comment]
The [Terms and Conditions](http://popit.poplus.org/about/privacy/) contain the following:

> We reserve the right to remove data or block accounts if the continued functioning of the wider PopIt site is threatened, or if your use of the site is clearly anti-social.

Which for now seems like enough. We can re-visit this in the future if necessary.
