### ISSUE TITLE
Un-hosting criteria

### ISSUE THREAD

**Issue by evdb** [mysociety/popit#15]
We might want to stop hosting some sites because they are not used or not suitable. What are our criteria for doing this?

* Site access/month falls below certain number?
* data stored of no value and not being maintained?
* site not being maintained so serving stale or wrong data?

**Comment by chrismytton** [comment]
I think the [Terms and Conditions](http://popit.poplus.org/about/privacy/) contain all that's needed for this:

> We reserve the right to remove data or block accounts if the continued functioning of the wider PopIt site is threatened, or if your use of the site is clearly anti-social.
