### ISSUE TITLE
ensure the CSV import adds a 'classification' for each Organization

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/popit#309]
Per #308, the import tool should make it clear what to do so that your Organizations get classified. It's currently unclear whether this is what the "Database Attribute" does, or whether it's possible it all.

**Comment by chrismytton** [comment]
The migration tool was removed in https://github.com/mysociety/popit/pull/371. The plan is to point people who want to import from CSV to http://everypolitician.org. Therefore closing this ticket.
