### ISSUE TITLE
Creating memberships inline

### ISSUE THREAD

**Issue by chrismytton** [mysociety/popit#346]
When creating a records it would be good if any inline memberships were extracted into the memberships collection and saved with a reference to the record that they were extracted from.

For example, if you created a person using the following JSON:

```json
{
  "memberships": [
    {
      "end_date": "1995-03-23",
      "start_date": "1987-03-21",
      "organization_id": "popit.eduskunta/party/r"
    }
  ],
  "links": [
    {
      "note": "Eduskunta.fi (en)",
      "url": "http://www.eduskunta.fi/triphome/bin/hex5000.sh?hnro=109&kieli=en"
    }
  ],
  "contact_details": [
    {
      "value": "+358 9 432 3100",
      "type": "phone"
    }
  ],
  "id": "popit.eduskunta/person/109",
  "name": "Jörn Donner",
  "family_name": "Donner",
  "given_names": "Jörn Johan",
  "identifiers": [
    {
      "scheme": "eduskunta.fi",
      "identifier": "109"
    }
  ],
  "email": "jorn.donner@parliament.fi",
  "birth_date": "1933-02-05",
  "image": "http://www.eduskunta.fi/fakta/edustaja/kuvat/109.jpg"
}
```

the membership property in the JSON should be extracted and turned into a separate membership record.

Currently the JSON would be accepted, but any memberships represented within it would be lost.

**Comment by struan** [comment]
This is awaiting is updating the API version to make live.
