### ISSUE TITLE
add bulk deletes to the API

### ISSUE THREAD

**Issue by mhl** [mysociety/popit#464]
e.g. to delete all organisations in one go. This is really slow to do one-by-one, and not trivial because of the pagination.

**Comment by chrismytton** [comment]
This will be even more useful once we've got the importer in place as people might want to undo an import.

**Comment by chrismytton** [comment]
Have opened a pull request for this here https://github.com/mysociety/popit-api/pull/128. Would still be useful to have a button for this in the UI.
