### ISSUE TITLE
Take steps to speed up loading of JSON into a new PopIt instance

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/popit#478]
quoting:

> I was forced today to recreate my whole instance because of an
> error in how I added the image field (as a hash instead of an array of
> hashes).
> And it takes over an hour to create every person.

>It would be better to have
> an entry point in the api that recieves a json with a lot of people, that
> would reduce this hour to some seconds. I think this is the most important
> feature.
>
> Let me explain:
> For every person I need to make 10 requests:
> 1) Check if the person exists
> 2) Crate/Update the person
> 3) Check if the block/party (organization) exists
> 4) Create/update the block
> 5) Check if the relation between the person and the block exists
> 6) Create the relation
> 7) Check if the chamber (organization) exists
> 8) Create/update the chamber
> 9) Check if the relation between the person and the chamber exists
> 10) Create the relation
>
> I have this optimized a bit, but it's VERY slow.
>
> Have a sample of the console output of my popit client/scraper:
>  
>
> Creating daniel-oscar-giacomino
> Already exists frente-para-la-victoria---pj
> Already exists hcdn
> Adding membership for 536ab75f7a30f333325767e0 as Diputado to
> 536ab4a77a30f33332576627
> Adding membership for 536ab75f7a30f333325767e0 as Integrante to
> 536ab4af7a30f3333257662c
>
> Creating veronica-gonzalez
> Already exists frente-para-la-victoria---pj
> Already exists hcdn
> Adding membership for 536ab7967a30f33332576800 as Diputado to
> 536ab4a77a30f33332576627
> Adding membership for 536ab7967a30f33332576800 as Integrante to
> 536ab4af7a30f3333257662c

**Comment by chrismytton** [comment]
Popolo import was added in https://github.com/mysociety/popit-api/pull/126 and https://github.com/mysociety/popit/pull/765.
