### ISSUE TITLE
"ID" when importing is ambiguous

### ISSUE THREAD

**Issue by henare** [mysociety/popit#497]
I didn't expect "ID" to refer to Twitter or Facebook. I expected it to be an identifier, e.g. "123" or something.
![selection_002](https://cloud.githubusercontent.com/assets/48945/3151630/7e9d8294-ea84-11e3-8760-a4520b114d88.png)

**Comment by chrismytton** [comment]
The migration tool was removed in https://github.com/mysociety/popit/pull/371. The plan is to point people who want to import from CSV to http://everypolitician.org. Therefore closing this ticket.
