### ISSUE TITLE
Memberships not imported via CSV

### ISSUE THREAD

**Issue by henare** [mysociety/popit#499]
I imported this list http://konklone.io/json/?id=8d2f210f500d7dccaf1b here http://transparencycamp.popit.mysociety.org/ and the organisation links didn't import :cry:

**Comment by chrismytton** [comment]
The migration tool was removed in https://github.com/mysociety/popit/pull/371. The plan is to point people who want to import from CSV to http://everypolitician.org. Therefore closing this ticket.
