### ISSUE TITLE
Update migration code for changed csv module interface

### ISSUE THREAD

**Issue by struan** [mysociety/popit#513]
The node csv module has totally changed its interface with version 0.4 such that our existing code doesn't work. As a short term measure I've set 0.3 exactly as a dependancy but we should redo the csv code to handle the new interface at some point.

**Comment by chrismytton** [comment]
The migration tool was removed in https://github.com/mysociety/popit/pull/371. The plan is to point people who want to import from CSV to http://everypolitician.org. Therefore closing this ticket.
