### ISSUE TITLE
Import csv fail when rows exceed 666(includind header)

### ISSUE THREAD

**Issue by thewayiam** [mysociety/popit#594]
![popit_import_fail](https://cloud.githubusercontent.com/assets/4479861/3887146/deaf0420-21eb-11e4-80ee-938c61f3e92a.jpg)
![popit_import](https://cloud.githubusercontent.com/assets/4479861/3887155/00f3f63a-21ec-11e4-80d0-660bebef937a.jpg)

**Comment by chrismytton** [comment]
The migration tool was removed in https://github.com/mysociety/popit/pull/371. The plan is to point people who want to import from CSV to http://everypolitician.org. Therefore closing this ticket.
