### ISSUE TITLE
Uploading an image via the UI results in a HTTP 504 error, even though the image is uploaded

### ISSUE THREAD

**Issue by jacksonj04** [mysociety/popit#683]
To recreate:

* Create a new organisation
* Edit the organisation
* Choose to add an image
* Upload an image from your local computer

The site will return a HTTP 504 error, but upon returning to the organisation page the image is uploaded as expected.

**Comment by andylolz** [comment]
I still see this issue every time I upload an image to the yournextmp popit instance.
