### ISSUE TITLE
Check/implement CORS for API calls

### ISSUE THREAD

**Issue by osfameron** [mysociety/popit#691]
I'm trying to access a popit instance from a Polymer web-component with a call like

```
            <core-ajax
                auto
                url="{{popit}}/api/v0.1/persons/{{person}}?embed=membership.organization"
                handleAs="json"
                withCredentials="true"
                on-core-response="{{handleResponse}}">
            </core-ajax>
```

and this isn't working due to same server origin policy.  I *think* the `withCredentials` parameter should make this work from the client side.  Is there something that needs to be enabled on server side for CORS to work?

**Comment by struan** [comment]
@scvnc, @osfameron This is now deployed.

**Comment by scvnc** [comment]
Thanks!
