### ISSUE TITLE
make the image-proxy URLs easily available

### ISSUE THREAD

**Issue by mhl** [mysociety/popit#707]
At the moment, the `image` and `images` elements in returned responses are links to the original image, e.g. (for one that's been uploaded to PopIt):

* http://yournextmp.popit.mysociety.org/persons/4507/image/5481e918b150e238702c062e

It's helpful to have easy access to the version behind that PopIt's image proxy, which would be:

* https://yournextmp.popit.mysociety.org/image-proxy/https%3A%2F%2Fyournextmp.popit.mysociety.org%2Fpersons%2Fimages%2F5481e918b150e238702c062e%2F4507/128/0

Since you can put a size at the end of that to get a thumbnail of a given size, it would frequently be useful to have that URL easily accessible too.  Alongside the `image` attribute, one could have `image_proxied` and similarly each object in the `images` array could have `url_proxied` as well as `url`.

**Comment by mhl** [comment]
I'm reopening this because the `proxy_image` and `proxy_url` elements don't work for this person, although the `image` and `url` references are fine:

* https://yournextmp.popit.mysociety.org/api/v0.1/persons/4322

**Comment by struan** [comment]
From IRC:

> struan: one other thing - the other image URLs are https when the request to the popit API is, and http    otherwise - it would be great if the proxied URLs behaved the same way
