### ISSUE TITLE
image-proxy returning 504 for some (all?) images

### ISSUE THREAD

**Issue by mhl** [mysociety/popit#719]
Some images are returned fine by the image proxy, while others are returning 504 Gateway Time-out. For example, this request:

* https://yournextmp.popit.mysociety.org/image-proxy/http%3A%2F%2Fyournextmp.popit.mysociety.org%2Fpersons%2F4521%2Fimage%2F5481e93ab150e238702c0648/120/0

Returns 504, whereas the following works:

* https://yournextmp.popit.mysociety.org/image-proxy/http%3A%2F%2Fyournextmp.popit.mysociety.org%2Fpersons%2F4493%2Fimage%2F5481e8f6b150e238702c061b/0/64

**Correction:** it was working but now fails, so presumably I was getting a cached version before.

The log in applogs doesn't help much:

```
127.0.0.1 - - [Sat, 10 Jan 2015 17:00:56 GMT] "GET /persons/4521/image/5481e93ab150e238702c0648 HTTP/1.1" 302 116 "-" "-"
127.0.0.1 - - [Sat, 10 Jan 2015 17:01:01 GMT] "GET /image-proxy/http%3A%2F%2Fyournextmp.popit.mysociety.org%2Fpersons%2F4521%2Fimage%2F5481e93ab150e238702c0648/120/0 HTTP/1.1" 504 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/39.0.2171.65 Chrome/39.0.2171.65 Safari/537.36"
```

**Comment by jpmckinney** [comment]
I'm looking into https://github.com/jpmckinney/image-proxy/issues/10 

Can you describe the steps to reproduce?

**Comment by struan** [comment]
Unfortunately not at the moment. There's not an obvious pattern we've been able to identify.

**Comment by jpmckinney** [comment]
But, basically, the PopIt instance is running for a while, receiving all sorts of requests, and then it starts returning errors? How long before errors occur (minutes, hours, days, or weeks)?

**Comment by struan** [comment]
Hours to a day I would say. It only started happening when a site with a bit of traffic started using the image proxy.

**Comment by jpmckinney** [comment]
The proxy seems to be working currently. How many times have you had to restart since discovering the issue?

504 is only returned if there's a timeout, which is 5s by default. Do you set a DELAY environment variable? Is it possible that all images were timing out? In the tests I had to set `http.globalAgent.maxSockets = 100;` because otherwise node would stop accepting new connections and all the late connections would time out. If PopIt is getting heavy usage, then maxSockets may need to be raised.

**Comment by struan** [comment]
Three or four times. We'll try upping the maxSockets and see if that helps. Thanks for the tip.

**Comment by mhl** [comment]
We haven't seen a recurrence of this, so I'm going to close the issue - thanks to everyone for figuring out both problems so quickly :)
