### ISSUE TITLE
Speed up deploys

### ISSUE THREAD

**Issue by chrismytton** [mysociety/popit#752]
Currently deploying popit takes around 40 seconds, this isn't too long but the site is down for the whole time the deploy is taking place.

Ideally the site should only need to be down for a few seconds while the app server is restarted. Installing npm modules can be done before the process is restarted, which just leaves compiling the assets. If we used a timestamped deploy, like alaveteli, then we could compile the updated assets into a timestamped directory then switch the symlink at the last moment.

**Comment by mhl** [comment]
:+1: This sounds like a good idea

@dracos also suggested that we could cover any downtime with Varnish's "grace" feature, if you define a health check for the backend:

* https://www.varnish-cache.org/trac/wiki/VCLExampleGrace
* https://www.varnish-cache.org/trac/wiki/BackendPolling

... but perhaps the downtime with timestamped deploys would be so low that wouldn't be worth it.

**Comment by chrismytton** [comment]
I've switched popit to using timestamped deploys now. The downtime is only the time it takes for the app server to come online. Once https://github.com/mysociety/popit/pull/775 is merged and with some tweaks to `deploy-vhost` it *might* be possible to do zero-downtime deploys, but this solution certainly improves things a lot for now.

**Comment by chrismytton** [comment]
Forgot to say, the slight disadvantage of this change is that deploys now take a bit longer from the developers POV because all the npm modules need to be re-installed every time the site is deployed. However this is probably something that can be worked around by symlinking/hardlinking the `node_modules` directory into the timestamped directory before installing modules, and I think the gains in minimizing downtime outweigh the slightly longer deploy times.

**Comment by dracos** [comment]
Yeah, symlinks are used like that on WDTK and the annual report (the `vendor` directory in the latter for all the gem installing).
