### ISSUE TITLE
Membership HTML view calls itself an Organization

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/popit#757]
e.g. https://parliament.popit.mysociety.org/memberships/c18-512-x-1983-06-09

"The details for this organization are also available in JSON" rather than "The details for this membership are also available in JSON"

**Comment by chrismytton** [comment]
Additionally the link to the JSON version of the membership has `#{membership.id}` in the url rather than the actual membership id.

**Comment by chrismytton** [comment]
Fixed in https://github.com/rubenarakelyan/popit/commit/8c9bdb12f3ed78e6f122149a2269ad4bf16fa911
