### ISSUE TITLE
Add reports/maps that generate submission competitive spirit

### ISSUE THREAD

**Issue by netclift** [mysociety/popit#780]
I am interested in whether such reports might generate additional crowd sourcing. 

I could imagine:

1. Constituencies by number of candidates submitted - with fewest easy to access (and get to work on)

2. Constituencies by percentage of data fields filled out - a way to give credit to the most complete constituencies overall 

3. Parties by most filled out percentage of data fields (perhaps with X or more candidates)

4. Some sort of view of activity by Scotland, England, Wales, and Northen Ireland.

5. An intensity map of the total data fields submitted by constituency and percentage of filled fields divided by candidate.

If promoted right these might help increase crowd-sourced contributions OR they might be "nice to have" features ... your call.

I suppose the most important measure of community activity by place could be awarded with a prize or party. :-)

**Comment by netclift** [comment]
Oops, I do see the constituencies report now. I'd simply add an option to quickly see those with the least candidates quickly.

**Comment by chrismytton** [comment]
@netclift This doesn't seem related to PopIt, was it supposed to go in the [yournextmp-popit](https://github.com/mysociety/yournextmp-popit) repo perhaps?
