### ISSUE TITLE
when POSTing a new image, there should be a parameter to say "put this first in images"

### ISSUE THREAD

**Issue by mhl** [mysociety/popit#796]
At the moment, if you POST an image with, say:

```
 curl -f \
    --request POST \
    --header "APIKey: $APIKEY" \
    -F notes="Some notes here" \
    -F image="@$FILENAME" \
    -F mime_type="$MIME_TYPE" \
    "https://yournextmp.popit.mysociety.org/api/v0.1/persons/$PERSON_ID/image"
```

That new image will be appended to the `images` array, rather than inserted first. It turns out that mostly we want newly uploaded images to go first in the image array (i.e. become the primary image that the `image` property is derived from), so it would be good if there were a `position=first` or `position=last` option that could be specified to control that.

**Comment by chrismytton** [comment]
Related to https://github.com/mysociety/popit/issues/62

**Comment by chrismytton** [comment]
Fixed in https://github.com/mysociety/popit-api/pull/134
