### ISSUE TITLE
Forgotten password emails delayed by SPF errors

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/popit#834]
I requested a Password Reset email this morning, but it took about 40 minutes to arrive. The headers contain the lines:

```
Received-SPF: softfail (google.com: domain of transitioning popit@mysociety.org does not designate 75.126.24.68 as permitted sender) client-ip=75.126.24.68;
Authentication-Results: mx.google.com;
       spf=softfail (google.com: domain of transitioning popit@mysociety.org does not designate 75.126.24.68 as permitted sender) smtp.mail=popit@mysociety.org
```

**Comment by mhl** [comment]
@Flupsy Perhaps you could take a look into this?

**Comment by Flupsy** [comment]
@tmtmtmtm could you paste the full headers please?

**Comment by Flupsy** [comment]
It looks like your mail rewriting service isn't using SRS, so Google objects to mail from `popit@mysociety.org` appearing to be sent directly from it.

**Comment by tmtmtmtm** [comment]
Ah, that's interesting to know. The text is a little misleading to me then (though perhaps anyone who's geeky enough to even *look* at mail headers should be able to read them better than I can?), but if it's not a problem with PopIt, there's presumably nothing to be done here...

**Comment by Flupsy** [comment]
Unfortunately the text is generated at Google :/
