### ISSUE TITLE
area id searches via API not returning results

### ISSUE THREAD

**Issue by kaerumy** [mysociety/popit#842]
No results for:
http://sinar-malaysia.popit.mysociety.org/api/v0.1/search/posts?q=id:p104

Results for:
http://sinar-malaysia.popit.mysociety.org/api/v0.1/search/posts?q=name:*Kelana*
http://sinar-malaysia.popit.mysociety.org/api/v0.1/search/posts?q=state:Selangor
http://sinar-malaysia.popit.mysociety.org/api/v0.1/search/posts?q=p104

**Comment by dracos** [comment]
If you want to query the area sub-object, you want http://sinar-malaysia.popit.mysociety.org/api/v0.1/search/posts?q=area.id:p104 which appears to work okay :)

**Comment by dracos** [comment]
The others are working because there's no name/state at top level to override, I think (might be wrong!), so you might want to use area.name and area.state for clarity.

**Comment by kaerumy** [comment]
Thanks for the clarification. sub area with dot works better and more accurately for us.
